name: Build project

on: [push, pull_request]

jobs:
    buildForAllSupportedPlatforms:
        name: Build for ${{ matrix.targetPlatform }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                targetPlatform:
                - StandaloneWindows # Build a Windows standalone.
                - StandaloneWindows64 # Build a Windows 64-bit standalone.
                - WebGL # WebGL.
        steps:
        - uses: actions/checkout@v4
          with:
                fetch-depth: 0
                lfs: true
        - uses: actions/cache@v3
          with:
                path: Library
                key: Library-${{ matrix.targetPlatform }}
                restore-keys: Library-
        - uses: game-ci/unity-builder@v4
          env:
                UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          with:
                targetPlatform: ${{ matrix.targetPlatform }}
                githubToken: ${{ secrets.GITHUB_TOKEN }}
        - uses: actions/upload-artifact@v3
          with:
                name: Build-${{ matrix.targetPlatform }}
                path: build/${{ matrix.targetPlatform }}
    deployPages:
            needs: buildForAllSupportedPlatforms
            name: Deploy to Itch.io 🚀
            runs-on: ubuntu-latest
            steps:
              - name: Checkout code
                uses: actions/checkout@v3
         
              - uses: actions/download-artifact@v2
                with:
                  name: Build-WebGL
                  path: build
         
              - name: Display structure of root files
                run: ls -R
                working-directory: build/WebGL
         
              - name: Deploy 🚀
                uses: JamesIves/github-pages-deploy-action@4.1.4
                with:
                  branch: itch-io
                  folder: build/WebGL
                  
              - uses: manleydev/butler-publish-itchio-action@master
                env:
                  BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
                  CHANNEL: HTML
                  ITCH_GAME: STAY-AWAY
                  ITCH_USER: studiodw
                  BRANCH: itch-io
                  PACKAGE: build/WebGL
